/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vistas;
import Modelo.Demografia_cliente;
import Controlador.Demografia_cliente_DAO;
import java.awt.Component;
import javax.swing.*;
import ConexionBD.ConexionBD;
import java.sql.SQLException;
/**
 *
 * @author Rafael Villaneda
 */
public class Cambios_clientes_Demograficos extends javax.swing.JFrame {

    /** Creates new form Cambios_clientes_Demograficos */
    public Cambios_clientes_Demograficos() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        caja_id_desc = new javax.swing.JTextField();
        caja_id_demografia1 = new javax.swing.JTextField();
        btn_rescribir = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        btn_Salir = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Visuales/user.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipady = -4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setText("Indentificador de la demografia: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 20, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setText("Descripcion de la demografia: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 96, 0, 0);
        getContentPane().add(jLabel3, gridBagConstraints);

        caja_id_desc.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.ipadx = 227;
        gridBagConstraints.ipady = 102;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 20, 0, 0);
        getContentPane().add(caja_id_desc, gridBagConstraints);

        caja_id_demografia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_id_demografia1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 52;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 18, 0, 0);
        getContentPane().add(caja_id_demografia1, gridBagConstraints);

        btn_rescribir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Visuales/Rescribir.png"))); // NOI18N
        btn_rescribir.setEnabled(false);
        btn_rescribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rescribirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 10, 0, 0);
        getContentPane().add(btn_rescribir, gridBagConstraints);

        btn_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Visuales/Limpiar.png"))); // NOI18N
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 9, 0, 0);
        getContentPane().add(btn_limpiar, gridBagConstraints);

        btn_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Visuales/salir.png"))); // NOI18N
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 18, 0, 0);
        getContentPane().add(btn_Salir, gridBagConstraints);

        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Visuales/Buscar_tablas.png"))); // NOI18N
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 18, 0, 0);
        getContentPane().add(btn_buscar, gridBagConstraints);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 231;
        gridBagConstraints.ipady = 94;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(32, 64, 13, 10);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        caja_id_demografia1.setText("");
        caja_id_desc.setText("");
        actualizarTabla("SELECT * FROM customerdemographics");
        btn_rescribir.setEnabled(false);
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btn_SalirActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        Demografia_cliente obj2=new Demografia_cliente();
        Demografia_cliente_DAO DAO=new Demografia_cliente_DAO();
        if(!caja_id_demografia1.getText().isEmpty()){
            obj2=DAO.buscar(caja_id_demografia1.getText());
            if(obj2!=null){
                caja_id_demografia1.setText(obj2.getId());
                caja_id_desc.setText(obj2.getDesc());
                caja_id_demografia1.setEnabled(false);
                caja_id_desc.setEnabled(true);
                btn_rescribir.setEnabled(true);
                actualizarTabla("SELECT * FROM customerdemographics");
            }else{
                JOptionPane.showMessageDialog(null,"No  se encontro el registro");
                actualizarTabla("SELECT * FROM customerdemographics");
            }
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_rescribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rescribirActionPerformed
        Demografia_cliente obj=new Demografia_cliente();
        Demografia_cliente_DAO DAO=new Demografia_cliente_DAO();
        if(!caja_id_demografia1.getText().isEmpty()){
            obj.setId(caja_id_demografia1.getText());
            obj.setDesc(caja_id_desc.getText());
            if(DAO.actualizar(obj)){
                JOptionPane.showMessageDialog(null,"Registro Actualizado correctamente");
                caja_id_demografia1.setEnabled(true);
                caja_id_desc.setEnabled(false);
                btn_rescribir.setEnabled(false);
                actualizarTabla("SELECT * FROM customerdemographics");
            }else{
                JOptionPane.showMessageDialog(null,"No se pudo actualizar el registro");
                actualizarTabla("SELECT * FROM customerdemographics");
                caja_id_demografia1.setEnabled(true);
                caja_id_desc.setEnabled(false);
            }
        }
    }//GEN-LAST:event_btn_rescribirActionPerformed

    private void caja_id_demografia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_id_demografia1ActionPerformed
       
    }//GEN-LAST:event_caja_id_demografia1ActionPerformed
    
    public void actualizarTabla(String consulta) {

	String url="jdbc:mysql://localhost:3306/northwind";
	String controlador="com.mysql.cj.jdbc.Driver";
	ResultSetTableModel modeloDatos=null;
	try {
	modeloDatos=new ResultSetTableModel(controlador, url,consulta);
	}catch (ClassNotFoundException e) {
	e.printStackTrace();
	}catch (SQLException e) {
	e.printStackTrace();
	}
	tabla.setModel(modeloDatos);
	}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cambios_clientes_Demograficos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cambios_clientes_Demograficos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cambios_clientes_Demograficos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cambios_clientes_Demograficos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cambios_clientes_Demograficos().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Salir;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_rescribir;
    private javax.swing.JTextField caja_id_demografia1;
    private javax.swing.JTextField caja_id_desc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables

}
