/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vistas;

/**
 *
 * @author Rafael Villaneda
 */
public class Cambios_clientes extends javax.swing.JFrame {

    /** Creates new form Cambios_clientes */
    public Cambios_clientes() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        caja_nombre_contacto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        caja_Nombre_compañia1 = new javax.swing.JTextField();
        caja_titulo_contacto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        caja_direccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        caja_id = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        caja_ciudad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        caja_region = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        caja_codigo_postal = new javax.swing.JTextField();
        caja_pais = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        caja_telefono = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        caja_fax = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btn_rescribir = new javax.swing.JButton();
        btn_Limpiar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Visuales/Modificar_Usuario.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 14)); // NOI18N
        jLabel2.setText("Nombre de la compañia:");

        caja_nombre_contacto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caja_nombre_contactoKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 14)); // NOI18N
        jLabel3.setText("Nombre de contacto:");

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 14)); // NOI18N
        jLabel4.setText("Titulo de contacto:");

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 14)); // NOI18N
        jLabel5.setText("Dirección: ");

        caja_direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caja_direccionKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 14)); // NOI18N
        jLabel6.setText("Indentificador");

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 14)); // NOI18N
        jLabel7.setText("Ciudad: ");

        caja_ciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_ciudadActionPerformed(evt);
            }
        });
        caja_ciudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caja_ciudadKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 14)); // NOI18N
        jLabel8.setText("Region: ");

        caja_region.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_regionActionPerformed(evt);
            }
        });
        caja_region.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caja_regionKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 14)); // NOI18N
        jLabel9.setText("Codigo postal: ");

        caja_codigo_postal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_codigo_postalActionPerformed(evt);
            }
        });
        caja_codigo_postal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caja_codigo_postalKeyTyped(evt);
            }
        });

        caja_pais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_paisActionPerformed(evt);
            }
        });
        caja_pais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caja_paisKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 14)); // NOI18N
        jLabel10.setText("Pais: ");

        caja_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_telefonoActionPerformed(evt);
            }
        });
        caja_telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caja_telefonoKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 14)); // NOI18N
        jLabel11.setText("Telefono: ");

        caja_fax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_faxActionPerformed(evt);
            }
        });
        caja_fax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caja_faxKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 14)); // NOI18N
        jLabel12.setText("Fax: ");

        btn_rescribir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Visuales/Rescribir.png"))); // NOI18N

        btn_Limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Visuales/Limpiar.png"))); // NOI18N
        btn_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LimpiarActionPerformed(evt);
            }
        });

        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Visuales/salir.png"))); // NOI18N
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel6)
                        .add(98, 98, 98)
                        .add(caja_id, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 157, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(jLabel2)
                        .add(28, 28, 28)
                        .add(caja_Nombre_compañia1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 157, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(3, 3, 3)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jLabel11)
                                .add(123, 123, 123)
                                .add(caja_telefono, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 157, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(jLabel12)
                                .add(158, 158, 158)
                                .add(caja_fax, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 157, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .add(2, 2, 2)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel3)
                            .add(jLabel4))
                        .add(49, 49, 49)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(caja_nombre_contacto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 157, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(caja_titulo_contacto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 157, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel5)
                            .add(jLabel7)
                            .add(jLabel8))
                        .add(118, 118, 118)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(caja_direccion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 157, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(caja_ciudad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 157, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(caja_region, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 157, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel9)
                            .add(jLabel10))
                        .add(88, 88, 88)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(caja_codigo_postal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 157, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(caja_pais, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 157, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 31, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(btn_rescribir)
                    .add(btn_Limpiar)
                    .add(btn_salir))
                .add(32, 32, 32))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 147, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(137, 137, 137))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 112, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(36, 36, 36)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(5, 5, 5)
                        .add(jLabel6))
                    .add(caja_id, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(11, 11, 11)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(5, 5, 5)
                        .add(jLabel2))
                    .add(caja_Nombre_compañia1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(11, 11, 11)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(5, 5, 5)
                                .add(jLabel3)
                                .add(25, 25, 25)
                                .add(jLabel4))
                            .add(layout.createSequentialGroup()
                                .add(caja_nombre_contacto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(11, 11, 11)
                                .add(caja_titulo_contacto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(11, 11, 11)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(12, 12, 12)
                                .add(jLabel5)
                                .add(18, 18, 18)
                                .add(jLabel7)
                                .add(20, 20, 20)
                                .add(jLabel8))
                            .add(layout.createSequentialGroup()
                                .add(caja_direccion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(11, 11, 11)
                                .add(caja_ciudad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(6, 6, 6)
                                .add(caja_region, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(11, 11, 11)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(5, 5, 5)
                                .add(jLabel9)
                                .add(32, 32, 32)
                                .add(jLabel10))
                            .add(layout.createSequentialGroup()
                                .add(caja_codigo_postal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(caja_pais, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(layout.createSequentialGroup()
                        .add(btn_rescribir)
                        .add(28, 28, 28)
                        .add(btn_Limpiar)
                        .add(29, 29, 29)
                        .add(btn_salir)))
                .add(9, 9, 9)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(14, 14, 14)
                        .add(jLabel11))
                    .add(caja_telefono, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(11, 11, 11)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(14, 14, 14)
                        .add(jLabel12))
                    .add(caja_fax, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void caja_nombre_contactoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_nombre_contactoKeyTyped
        char car = evt.getKeyChar();
        if(Character.isLetter(car) || Character.isSpaceChar(car)){}else{
            evt.consume();
        }
    }//GEN-LAST:event_caja_nombre_contactoKeyTyped

    private void caja_direccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_direccionKeyTyped
        char car = evt.getKeyChar();
        if(Character.isLetter(car) || Character.isSpaceChar(car) || Character.isDigit(car)){}else{
            evt.consume();
        }
    }//GEN-LAST:event_caja_direccionKeyTyped

    private void caja_ciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_ciudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja_ciudadActionPerformed

    private void caja_ciudadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_ciudadKeyTyped
        char car = evt.getKeyChar();
        if(Character.isLetter(car) || Character.isSpaceChar(car) || car=='.'){}else{
            evt.consume();
        }
    }//GEN-LAST:event_caja_ciudadKeyTyped

    private void caja_regionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_regionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja_regionActionPerformed

    private void caja_regionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_regionKeyTyped
        char car = evt.getKeyChar();
        if(Character.isLetter(car) || Character.isSpaceChar(car)){}else{
            evt.consume();
        }
    }//GEN-LAST:event_caja_regionKeyTyped

    private void caja_codigo_postalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_codigo_postalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja_codigo_postalActionPerformed

    private void caja_codigo_postalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_codigo_postalKeyTyped
        char car = evt.getKeyChar();
        if(Character.isLetter(car) || Character.isSpaceChar(car) || Character.isDigit(car)){}else{
            evt.consume();
        }
    }//GEN-LAST:event_caja_codigo_postalKeyTyped

    private void caja_paisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_paisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja_paisActionPerformed

    private void caja_paisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_paisKeyTyped
        char car = evt.getKeyChar();
        if(Character.isLetter(car) || Character.isSpaceChar(car)){}else{
            evt.consume();
        }
    }//GEN-LAST:event_caja_paisKeyTyped

    private void caja_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja_telefonoActionPerformed

    private void caja_telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_telefonoKeyTyped
        char car = evt.getKeyChar();
        if(Character.isDigit(car) || car=='-' || car=='(' || car==')'){}else{
            evt.consume();
        }
    }//GEN-LAST:event_caja_telefonoKeyTyped

    private void caja_faxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_faxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja_faxActionPerformed

    private void caja_faxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_faxKeyTyped
        char car = evt.getKeyChar();
        if(Character.isDigit(car) || car=='-' || car=='(' || car==')'){}else{
            evt.consume();
        }
    }//GEN-LAST:event_caja_faxKeyTyped

    private void btn_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LimpiarActionPerformed
        caja_id.setText("");
        caja_Nombre_compañia1.setText("");
        caja_nombre_contacto.setText("");
        caja_titulo_contacto.setText("");
        caja_direccion.setText("");
        caja_ciudad.setText("");
        caja_region.setText("");
        caja_codigo_postal.setText("");
        caja_pais.setText("");
        caja_telefono.setText("");
        caja_fax.setText("");
    }//GEN-LAST:event_btn_LimpiarActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btn_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cambios_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cambios_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cambios_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cambios_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cambios_clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Limpiar;
    private javax.swing.JButton btn_rescribir;
    private javax.swing.JButton btn_salir;
    private javax.swing.JTextField caja_Nombre_compañia1;
    private javax.swing.JTextField caja_ciudad;
    private javax.swing.JTextField caja_codigo_postal;
    private javax.swing.JTextField caja_direccion;
    private javax.swing.JTextField caja_fax;
    private javax.swing.JTextField caja_id;
    private javax.swing.JTextField caja_nombre_contacto;
    private javax.swing.JTextField caja_pais;
    private javax.swing.JTextField caja_region;
    private javax.swing.JTextField caja_telefono;
    private javax.swing.JTextField caja_titulo_contacto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

}
