/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vistas;
import ConexionBD.ConexionBD;
import java.sql.SQLException;

/**
 *
 * @author Rafael Villaneda
 */
public class Consultas_clientes extends javax.swing.JFrame {
    boolean activos []=new boolean [10];
    /** Creates new form Consultas_clientes */
    public Consultas_clientes() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        caja_nombre_contacto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        caja_Nombre_compañia1 = new javax.swing.JTextField();
        caja_titulo_contacto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        caja_direccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        caja_id = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        caja_ciudad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        caja_region = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        caja_codigo_postal = new javax.swing.JTextField();
        caja_pais = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        caja_telefono = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        caja_fax = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btn_Buscar = new javax.swing.JButton();
        btn_Limpiar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consultas de clientes");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Visuales/user.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.gridheight = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 14)); // NOI18N
        jLabel2.setText("Nombre de la compañia:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 11, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        caja_nombre_contacto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                caja_nombre_contactoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caja_nombre_contactoKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 28, 0, 0);
        getContentPane().add(caja_nombre_contacto, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 14)); // NOI18N
        jLabel3.setText("Nombre de contacto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 13, 0, 0);
        getContentPane().add(jLabel3, gridBagConstraints);

        caja_Nombre_compañia1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                caja_Nombre_compañia1KeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 28, 0, 0);
        getContentPane().add(caja_Nombre_compañia1, gridBagConstraints);

        caja_titulo_contacto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                caja_titulo_contactoKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 65, 0, 0);
        getContentPane().add(caja_titulo_contacto, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 14)); // NOI18N
        jLabel4.setText("Titulo de contacto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 10, 0, 0);
        getContentPane().add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 14)); // NOI18N
        jLabel5.setText("Dirección: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 10, 0, 0);
        getContentPane().add(jLabel5, gridBagConstraints);

        caja_direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                caja_direccionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caja_direccionKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 65, 0, 0);
        getContentPane().add(caja_direccion, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 14)); // NOI18N
        jLabel6.setText("Indentificador");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 11, 0, 0);
        getContentPane().add(jLabel6, gridBagConstraints);

        caja_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                caja_idKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caja_idKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 28, 0, 0);
        getContentPane().add(caja_id, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 14)); // NOI18N
        jLabel7.setText("Ciudad: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 10, 0, 0);
        getContentPane().add(jLabel7, gridBagConstraints);

        caja_ciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_ciudadActionPerformed(evt);
            }
        });
        caja_ciudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                caja_ciudadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caja_ciudadKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 65, 0, 0);
        getContentPane().add(caja_ciudad, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 14)); // NOI18N
        jLabel8.setText("Region: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 0, 0);
        getContentPane().add(jLabel8, gridBagConstraints);

        caja_region.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_regionActionPerformed(evt);
            }
        });
        caja_region.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                caja_regionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caja_regionKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 65, 0, 0);
        getContentPane().add(caja_region, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 14)); // NOI18N
        jLabel9.setText("Codigo postal: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 0, 0, 0);
        getContentPane().add(jLabel9, gridBagConstraints);

        caja_codigo_postal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_codigo_postalActionPerformed(evt);
            }
        });
        caja_codigo_postal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                caja_codigo_postalKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caja_codigo_postalKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 65, 0, 0);
        getContentPane().add(caja_codigo_postal, gridBagConstraints);

        caja_pais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_paisActionPerformed(evt);
            }
        });
        caja_pais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                caja_paisKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caja_paisKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 65, 0, 0);
        getContentPane().add(caja_pais, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 14)); // NOI18N
        jLabel10.setText("Pais: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 0, 0, 0);
        getContentPane().add(jLabel10, gridBagConstraints);

        caja_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_telefonoActionPerformed(evt);
            }
        });
        caja_telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                caja_telefonoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caja_telefonoKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 65, 0, 0);
        getContentPane().add(caja_telefono, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 14)); // NOI18N
        jLabel11.setText("Telefono: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 1, 0, 0);
        getContentPane().add(jLabel11, gridBagConstraints);

        caja_fax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_faxActionPerformed(evt);
            }
        });
        caja_fax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                caja_faxKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                caja_faxKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 65, 0, 0);
        getContentPane().add(caja_fax, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 14)); // NOI18N
        jLabel12.setText("Fax: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 1, 0, 0);
        getContentPane().add(jLabel12, gridBagConstraints);

        btn_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Visuales/all.png"))); // NOI18N
        btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 1, 22, 0);
        getContentPane().add(btn_Buscar, gridBagConstraints);

        btn_Limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Visuales/Limpiar.png"))); // NOI18N
        btn_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LimpiarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 13, 22, 0);
        getContentPane().add(btn_Limpiar, gridBagConstraints);

        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Visuales/salir.png"))); // NOI18N
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 1, 22, 0);
        getContentPane().add(btn_salir, gridBagConstraints);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabla);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 21;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 21;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 663;
        gridBagConstraints.ipady = 542;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 18, 22, 10);
        getContentPane().add(jScrollPane2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void caja_nombre_contactoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_nombre_contactoKeyTyped
        char car = evt.getKeyChar();
        if(Character.isLetter(car) || Character.isSpaceChar(car)){}else{
            evt.consume();
        }
    }//GEN-LAST:event_caja_nombre_contactoKeyTyped

    private void caja_direccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_direccionKeyTyped
        char car = evt.getKeyChar();
        if(Character.isLetter(car) || Character.isSpaceChar(car) || Character.isDigit(car)){}else{
            evt.consume();
        }
    }//GEN-LAST:event_caja_direccionKeyTyped

    private void caja_ciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_ciudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja_ciudadActionPerformed

    private void caja_ciudadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_ciudadKeyTyped
        char car = evt.getKeyChar();
        if(Character.isLetter(car) || Character.isSpaceChar(car) || car=='.'){}else{
            evt.consume();
        }
    }//GEN-LAST:event_caja_ciudadKeyTyped

    private void caja_regionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_regionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja_regionActionPerformed

    private void caja_regionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_regionKeyTyped
        char car = evt.getKeyChar();
        if(Character.isLetter(car) || Character.isSpaceChar(car)){}else{
            evt.consume();
        }
    }//GEN-LAST:event_caja_regionKeyTyped

    private void caja_codigo_postalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_codigo_postalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja_codigo_postalActionPerformed

    private void caja_codigo_postalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_codigo_postalKeyTyped
        char car = evt.getKeyChar();
        if(Character.isLetter(car) || Character.isSpaceChar(car) || Character.isDigit(car)){}else{
            evt.consume();
        }
    }//GEN-LAST:event_caja_codigo_postalKeyTyped

    private void caja_paisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_paisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja_paisActionPerformed

    private void caja_paisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_paisKeyTyped
        char car = evt.getKeyChar();
        if(Character.isLetter(car) || Character.isSpaceChar(car)){}else{
            evt.consume();
        }
    }//GEN-LAST:event_caja_paisKeyTyped

    private void caja_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja_telefonoActionPerformed

    private void caja_telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_telefonoKeyTyped
        char car = evt.getKeyChar();
        if(Character.isDigit(car) || car=='-' || car=='(' || car==')'){}else{
            evt.consume();
        }
    }//GEN-LAST:event_caja_telefonoKeyTyped

    private void caja_faxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_faxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja_faxActionPerformed

    private void caja_faxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_faxKeyTyped
        char car = evt.getKeyChar();
        if(Character.isDigit(car) || car=='-' || car=='(' || car==')'){}else{
            evt.consume();
        }
    }//GEN-LAST:event_caja_faxKeyTyped

    public void actualizarTabla(String consulta) {

	String url="jdbc:mysql://localhost:3306/northwind";
	String controlador="com.mysql.cj.jdbc.Driver";
	ResultSetTableModel modeloDatos=null;
	try {
	modeloDatos=new ResultSetTableModel(controlador, url,consulta);
	}catch (ClassNotFoundException e) {
	e.printStackTrace();
	}catch (SQLException e) {
	e.printStackTrace();
	}
	tabla.setModel(modeloDatos);
	}
    
    private void btn_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LimpiarActionPerformed
        caja_id.setText("");
        caja_Nombre_compañia1.setText("");
        caja_nombre_contacto.setText("");
        caja_titulo_contacto.setText("");
        caja_direccion.setText("");
        caja_ciudad.setText("");
        caja_region.setText("");
        caja_codigo_postal.setText("");
        caja_pais.setText("");
        caja_telefono.setText("");
        caja_fax.setText("");
        actualizarTabla("SELECT * FROM customers");
    }//GEN-LAST:event_btn_LimpiarActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarActionPerformed
       actualizarTabla("SELECT * FROM customers");
    }//GEN-LAST:event_btn_BuscarActionPerformed

    private void caja_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_idKeyReleased
        //System.out.println(caja_id.getText());
        String agregado=caja_id.getText();
        String consulta="SELECT * FROM customers WHERE CustomerID LIKE '"+agregado+"%'";
        actualizarTabla(consulta);
        

                
    }//GEN-LAST:event_caja_idKeyReleased

    private void caja_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_idKeyTyped
        char car = evt.getKeyChar();
	if(Character.isLetter(car)){
            }else{
		evt.consume();
	}
    }//GEN-LAST:event_caja_idKeyTyped

    private void caja_Nombre_compañia1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_Nombre_compañia1KeyReleased
        String agregado=caja_Nombre_compañia1.getText();
        String consulta="SELECT * FROM customers WHERE CompanyName LIKE '"+agregado+"%'";
        actualizarTabla(consulta);
        
    }//GEN-LAST:event_caja_Nombre_compañia1KeyReleased

    private void caja_nombre_contactoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_nombre_contactoKeyReleased
        String agregado=caja_nombre_contacto.getText();
        String consulta="SELECT * FROM customers WHERE contactName LIKE '"+agregado+"%'";
        actualizarTabla(consulta);
        
    }//GEN-LAST:event_caja_nombre_contactoKeyReleased

    private void caja_titulo_contactoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_titulo_contactoKeyReleased
        String agregado=caja_titulo_contacto.getText();
        String consulta="SELECT * FROM customers WHERE contactTitle LIKE '"+agregado+"%'";
        actualizarTabla(consulta);
        
    }//GEN-LAST:event_caja_titulo_contactoKeyReleased

    private void caja_direccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_direccionKeyReleased
        String agregado=caja_titulo_contacto.getText();
        String consulta="SELECT * FROM customers WHERE address LIKE '"+agregado+"%'";
        actualizarTabla(consulta);
    }//GEN-LAST:event_caja_direccionKeyReleased

    private void caja_ciudadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_ciudadKeyReleased
        String agregado=caja_ciudad.getText();
        String consulta="SELECT * FROM customers WHERE city LIKE '"+agregado+"%'";
        actualizarTabla(consulta);
    }//GEN-LAST:event_caja_ciudadKeyReleased

    private void caja_regionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_regionKeyReleased
        String agregado=caja_region.getText();
        String consulta="SELECT * FROM customers WHERE region LIKE '"+agregado+"%'";
        actualizarTabla(consulta);
    }//GEN-LAST:event_caja_regionKeyReleased

    private void caja_codigo_postalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_codigo_postalKeyReleased
       String agregado=caja_codigo_postal.getText();
        String consulta="SELECT * FROM customers WHERE postalcode LIKE '"+agregado+"%'";
        actualizarTabla(consulta);
    }//GEN-LAST:event_caja_codigo_postalKeyReleased

    private void caja_paisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_paisKeyReleased
        String agregado=caja_pais.getText();
        String consulta="SELECT * FROM customers WHERE country LIKE '"+agregado+"%'";
        actualizarTabla(consulta);
    }//GEN-LAST:event_caja_paisKeyReleased

    private void caja_telefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_telefonoKeyReleased
        String agregado=caja_telefono.getText();
        String consulta="SELECT * FROM customers WHERE phone LIKE '"+agregado+"%'";
        actualizarTabla(consulta);
    }//GEN-LAST:event_caja_telefonoKeyReleased

    private void caja_faxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja_faxKeyReleased
        String agregado=caja_fax.getText();
        String consulta="SELECT * FROM customers WHERE Fax LIKE '"+agregado+"%'";
        actualizarTabla(consulta);
    }//GEN-LAST:event_caja_faxKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultas_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultas_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultas_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultas_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultas_clientes().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JButton btn_Limpiar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JTextField caja_Nombre_compañia1;
    private javax.swing.JTextField caja_ciudad;
    private javax.swing.JTextField caja_codigo_postal;
    private javax.swing.JTextField caja_direccion;
    private javax.swing.JTextField caja_fax;
    private javax.swing.JTextField caja_id;
    private javax.swing.JTextField caja_nombre_contacto;
    private javax.swing.JTextField caja_pais;
    private javax.swing.JTextField caja_region;
    private javax.swing.JTextField caja_telefono;
    private javax.swing.JTextField caja_titulo_contacto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables

}
